default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rabbitmq_publisher_development

test:
  <<: *default
  database: rabbitmq_publisher_test

production:
  <<: *default
  database: rabbitmq_publisher_production
