# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbb92122a4f7b9cceeca19b949f92add896d5c6a99fae23a835de3994e0c0b29741e457b3a20936215bc2129ac4eb2a7a6ae4db843fce50249d78f4de6ab152e

test:
  secret_key_base: 99d8260313622c1cd758acdd097971547543ef5568ef86654147f158a97882aefb0277b41b5ea5f5a4f1e7bb086fe6d0183df5db12e7625404ce4548d1aee8fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
